[package]
name = "rstask"
version = "0.26.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "rstask"
path = "src/main.rs"

[dependencies]
rstask-core = { path = "../rstask-core" }
anyhow.workspace = true
